site_name: The Bike Project
site_url: https://alec-bike.github.io

nav:
  - Home: index.md

theme:
  name: material
  font:
    text: Cairo
    code: Cairo Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.tilde
