[project]
name = "alec-bike.github.io"
version = "0.1.0"
description = "Electric bike project."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mdformat-mkdocs>=4.1.1",
    "mkdocs-material>=9.5.49",
]
