[project]
name = "alec-bike.github.io"
version = "0.1.0"
description = "The Bike Project."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-github-admonitions-plugin>=0.1.1",
    "mkdocs-material>=9.6.16",
]
